language: JS
services: 
    - docker

before_install:
    - docker build -t davoasrn/docker-react -f Dockerfile.dev .

script:
    -  docker run davoasrn/docker-react npm run test -- --coverage
